# Generated by Django 4.2.1 on 2023-05-11 20:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('birth', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1445)])),
                ('death', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1445)])),
                ('rank', models.PositiveIntegerField(default=0)),
                ('child', models.ManyToManyField(blank=True, to='tree.person')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.person')),
            ],
        ),
    ]
