# Generated by Django 4.2.1 on 2023-05-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_alter_person_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='child',
        ),
    ]
