# Generated by Django 4.2.1 on 2023-05-11 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_remove_person_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1445)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='death',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1445)]),
        ),
    ]
