# Generated by Django 4.2.1 on 2023-05-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_alter_person_birth_alter_person_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
