# Generated by Django 4.2.1 on 2023-05-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_alter_person_birth_alter_person_death_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='death',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
