# Generated by Django 4.2.1 on 2023-05-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0010_remove_person_birth_remove_person_death"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
